#pragma once

#define MUVI_CFG_WORKER_BUF_SIZE_ELEMS 3
#define AUDIO_BUFFER_SIZE (2 << 11)
#define CHUNK_SIZE (2 << 10)

#define DEFAULT_COLORMAP ((int) cv::COLORMAP_RAINBOW)
#define DEFAULT_WIDTH 1024
#define DEFAULT_HEIGHT 768